### ISSUE TITLE
Line ending tests break in 2.7

### ISSUE THREAD

**Issue by jonsiddle** [rtyler/cheetah#3]
There are 6 failures which are line endings tests. Python 2.7
changed the behaviour of the compile() builtin (change documented
at http://docs.python.org/dev/whatsnew/2.7.html). The following
minimally reproduces the change:

c = compile('x="""\r\nx\r\n"""', 'file', 'exec')
exec(c, globals(), locals())

print x == "\nx\n"

Under 2.7 this prints "True". Under earlier versions of python, it prints
"False".

I can't see a way round this short of replacing all in-string literal 
newlines
with "\r\n" or "\r". This would require pre-parsing the template to find
the strings. Hopefully there's a nicer way.

Here, we don't actually care that literal line endings get converted to UNIX
line endings; does this matter to anyone? Would it be easier to require
non-UNIX line endings to be escaped?

**Comment by rtyler** [comment]
Fixed in the latest push to my master branch
